"""A dedicated visible Chrome/Edge profile, owned by one browser thread.

Login is performed by the user on Douyin. Only identity responses generated by
that page are read; cookies/tokens are never exported into application records.
"""
import os
import queue
import re
import shutil
import threading
import time
from concurrent.futures import Future
from urllib.parse import urlsplit

from .core import Cancelled
from .models import now

HOME = 'https://creator.douyin.com/'
IDENTITY_PATHS = {
    '/aweme/v1/creator/pc/user/info/',
    '/aweme/v1/creator/user/info/',
    '/web/api/media/user/info/',
}


def is_identity_url(url):
    parsed = urlsplit(url)
    return parsed.scheme == 'https' and parsed.netloc == 'creator.douyin.com' and parsed.path in IDENTITY_PATHS


def parse_identity(url, payload):
    if not is_identity_url(url) or not isinstance(payload, dict) or type(payload.get('status_code')) is not int or payload['status_code'] != 0:
        return None
    user = payload.get('user') if urlsplit(url).path == '/web/api/media/user/info/' else payload
    if not isinstance(user, dict):
        return None
    uid = user.get('uid')
    if not isinstance(uid, (str, int)) or isinstance(uid, bool) or not re.fullmatch(r'[1-9][0-9]{0,29}', str(uid)):
        return None
    profile = user.get('user_profile') or {}
    if not isinstance(profile, dict):
        profile = {}
    name = profile.get('nick_name') or user.get('nickname')
    name = name.strip() if isinstance(name, str) else ''
    return {'platform': 'douyin', 'platform_user_id': str(uid),
            'display_name': name or ('抖音账号 ID ' + str(uid)),
            'name_observed': bool(name), 'provider_id': 'douyin_browser'}


class LoginBinding:
    def __init__(self, repository):
        self.repository = repository
        fixed = repository.setting('fixed_account', {})
        if fixed.get('provider_id') == 'douyin_browser' and fixed.get('platform_user_id'):
            # The persistent, app-owned browser profile is the source of the
            # saved session. Publishing still rechecks it on the official page.
            repository.save_setting('douyin_session', {
                'state': 'SAVED', 'message': '登录状态已保存，发布前自动检查', 'checked_at': now(),
            })
        else:
            self.state('UNVERIFIED', '点击登录抖音，检查本机登录状态')

    def state(self, state, message):
        fixed = self.repository.setting('fixed_account', {})
        if fixed and state != 'CONNECTED':
            fixed['verified'] = False
            self.repository.save_setting('fixed_account', fixed)
        self.repository.save_setting('douyin_session', {'state': state, 'message': message, 'checked_at': now()})

    def connected(self, account):
        if account.get('platform') != 'douyin' or account.get('provider_id') != 'douyin_browser' or not account.get('platform_user_id'):
            raise ValueError('未取得抖音账号身份，请重新登录')
        fixed = self.repository.setting('fixed_account', {})
        if fixed and (fixed.get('platform_user_id') != account['platform_user_id'] or fixed.get('provider_id') != 'douyin_browser'):
            message = '当前登录与固定账号不一致，请在抖音页面切回原固定账号；未更换发布目标'
            self.state('ACCOUNT_MISMATCH', message)
            raise ValueError(message)
        # Preserve an observed nickname when a fast response only contains UID.
        if not account.get('name_observed') and fixed.get('name_observed'):
            account = dict(account, display_name=fixed['display_name'], name_observed=True)
        saved = dict(account, verified=True, verified_at=now())
        self.repository.save_setting('fixed_account', saved)
        self.state('CONNECTED', '已登录；发布前仍会再次检查账号')
        return saved


class DouyinBrowserSession:
    def __init__(self, repository):
        self.repository = repository
        self.binding = LoginBinding(repository)
        self.profile = repository.root / 'browser_profiles' / 'douyin'
        self._queue = queue.Queue()
        self._stop = threading.Event()
        self._thread = None
        self._lock = threading.Lock()
        self._context = self._page = self._playwright = None
        self._candidate = None
        self._monitor = False
        self._close_after_login = False
        self._restoring = False

    def _check(self, cancel):
        if cancel.is_set() or self._stop.is_set():
            raise Cancelled('已停止等待登录；可以再次点击登录抖音')

    def _call(self, operation, cancel, progress, timeout):
        with self._lock:
            if self._stop.is_set():
                raise RuntimeError('登录窗口已关闭，请重新打开软件')
            if self._thread is None:
                self._thread = threading.Thread(target=self._loop, name='P009-DouyinBrowser', daemon=True)
                self._thread.start()
            future = Future()
            self._queue.put((future, operation, cancel, progress, timeout))
        # Browser work stays on its owner thread even when the Qt worker changes.
        return future.result()

    def login(self, cancel, progress, timeout=300):
        return self._call('login', cancel, progress, timeout)

    def switch_account(self, cancel, progress, timeout=300):
        """Forget this tool's dedicated profile, then let the user log in again."""
        return self._call('switch_account', cancel, progress, timeout)

    def open_backend(self, cancel, progress):
        """Open the official creator backend and leave it open for the user."""
        return self._call('open_backend', cancel, progress, 30)

    def restore(self, cancel):
        return self._call('restore', cancel, lambda _: None, 20)

    def identity(self, cancel):
        return self._call('identity', cancel, lambda _: None, 20)

    def execute(self, action, cancel, progress):
        """Run a publisher operation on the same browser-owning thread."""
        return self._call(action, cancel, progress, 20)

    def _loop(self):
        try:
            while not self._stop.is_set():
                try:
                    future, operation, cancel, progress, timeout = self._queue.get(timeout=.1)
                except queue.Empty:
                    if self._page is not None:
                        try:
                            if self._page.is_closed():
                                self._dispose()
                                self._remember_closed_window()
                            else:
                                self._page.wait_for_timeout(100)
                                if self._close_after_login and self.repository.setting('douyin_session',{}).get('state')=='CONNECTED':
                                    self._dispose();self._close_after_login=False
                        except Exception:
                            self._dispose()
                            self._remember_closed_window()
                    continue
                try:
                    self._check(cancel)
                    self._restoring = operation == 'restore'
                    self._close_after_login = operation in ('login', 'switch_account')
                    if callable(operation):
                        result = operation(self, cancel, progress)
                    elif operation == 'open_backend':
                        result = self._open_backend(cancel, progress)
                    elif operation == 'switch_account':
                        result = self._switch_account(cancel, progress, timeout)
                    else:
                        result = self._login(cancel, progress, timeout, operation == 'login')
                    if operation in ('login', 'switch_account'):
                        self._dispose();self._close_after_login=False
                        progress(('已切换账号' if operation == 'switch_account' else '登录成功')+'，已关闭专用浏览器；发布时自动重新打开')
                    if self._restoring:self._dispose()
                    future.set_result(result)
                except (Cancelled, ValueError, RuntimeError) as exc:
                    if operation != 'open_backend' and not callable(operation) and self.repository.setting('douyin_session', {}).get('state') != 'ACCOUNT_MISMATCH':
                        self.binding.state('UNVERIFIED', str(exc))
                    future.set_exception(exc)
                except Exception as exc:
                    message = '抖音页面检查失败：'+str(exc)
                    if operation != 'open_backend' and not callable(operation):self.binding.state('ERROR', message)
                    future.set_exception(RuntimeError(message))
                finally:
                    if self._restoring:self._dispose()
                    self._restoring=False
        finally:
            self._dispose()
            self._remember_closed_window()
            while True:
                try:
                    item = self._queue.get_nowait()
                except queue.Empty:
                    break
                item[0].set_exception(Cancelled('软件已关闭'))

    def _ensure_browser(self):
        if self._page is not None and not self._page.is_closed():
            try:
                # A page object can outlive the browser connection.
                self._page.evaluate('1')
                return
            except Exception:
                pass
        self._dispose()
        from playwright.sync_api import sync_playwright
        self.profile.mkdir(parents=True, exist_ok=True, mode=0o700)
        if os.name != 'nt':self.profile.chmod(0o700)
        self._playwright = sync_playwright().start()
        channels = ('msedge', 'chrome') if os.name == 'nt' else ('chrome', 'msedge')
        last_error=None
        # Retry only browser initialization. Never replay an upload or submit.
        for channel in channels:
            for attempt in range(2):
                context=None
                try:
                    context=self._playwright.chromium.launch_persistent_context(
                        str(self.profile),channel=channel,headless=self._restoring,
                        accept_downloads=False,viewport=None,timeout=15000,args=['--no-first-run'])
                    page=self._select_browser_page(context)
                    page.evaluate('1')
                    page.set_default_timeout(10000)
                    page.on('response',self._response)
                    self._context=context;self._page=page
                    return
                except Exception as exc:
                    last_error=exc
                    if context is not None:
                        try:context.close()
                        except Exception:pass
        self._dispose()
        raise RuntimeError('无法建立浏览器页面，请关闭重复的登录窗口后重试；并确认 Chrome 或 Edge 可正常打开。具体原因：'+str(last_error))

    @staticmethod
    def _select_browser_page(context):
        pages=[page for page in context.pages if not page.is_closed()]
        # Keep the last live page: closing it first can terminate Edge/Chrome.
        page=pages[0] if pages else context.new_page()
        for extra in pages[1:]:
            try:extra.close()
            except Exception:pass
        return page

    def _remember_closed_window(self):
        fixed = self.repository.setting('fixed_account', {})
        if fixed.get('provider_id') == 'douyin_browser' and fixed.get('platform_user_id'):
            self.repository.save_setting('douyin_session', {
                'state': 'SAVED', 'message': '登录状态已保存，发布前自动检查', 'checked_at': now(),
            })
        else:
            self.binding.state('UNVERIFIED', '点击登录抖音，检查本机登录状态')

    def _open_backend(self, cancel, progress):
        self._ensure_browser()
        self._check(cancel)
        self._page.bring_to_front()
        self._page.goto(HOME, wait_until='domcontentloaded', timeout=15000)
        progress('已打开抖音创作者后台')
        return {'message': '已打开抖音创作者后台'}

    def _switch_account(self, cancel, progress, timeout):
        """This intentionally affects only P009's browser profile, never Chrome's own profile."""
        self._dispose()
        if self.profile.exists():
            shutil.rmtree(self.profile)
        self.repository.save_setting('fixed_account', {})
        self.binding.state('UNVERIFIED', '请在抖音官方窗口登录要切换的新账号')
        progress('已清除本工具保存的登录状态，正在打开抖音官方登录窗口')
        return self._login(cancel, progress, timeout, True)

    def _response(self, response):
        if not is_identity_url(response.url):
            return
        try:
            body = response.json()
        except Exception:
            return
        if not isinstance(body, dict):
            return
        if body.get('status_code') in (4, 8):
            self._candidate = None
            self.binding.state('WAITING_LOGIN', '请在抖音官方窗口扫码登录；如有验证码，请在页面中完成')
            return
        identity = parse_identity(response.url, body)
        if identity:
            if self._candidate and self._candidate['platform_user_id'] == identity['platform_user_id'] and self._candidate.get('name_observed') and not identity.get('name_observed'):
                identity = dict(identity, display_name=self._candidate['display_name'], name_observed=True)
            self._candidate = identity
            if self._monitor:
                try:
                    self.binding.connected(identity)
                except ValueError:
                    self._candidate = None

    def _login(self, cancel, progress, timeout, allow_wait):
        self._monitor = False
        self._candidate = None
        self.binding.state('CHECKING', '正在自动检查保存的登录状态' if self._restoring else '正在打开抖音官方登录窗口')
        progress('正在打开抖音官方窗口；扫码和验证码均在抖音页面完成')
        self._ensure_browser()
        self._check(cancel)
        if not self._restoring:self._page.bring_to_front()
        self._page.goto(HOME, wait_until='domcontentloaded', timeout=15000)
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            self._check(cancel)
            if self._page.is_closed():
                raise Cancelled('抖音窗口已关闭；可以再次点击登录')
            if self._candidate:
                # Let the normal page's other identity responses settle.
                self._page.wait_for_timeout(800)
                self._check(cancel)
                if self._candidate:
                    result = self.binding.connected(self._candidate)
                    self._monitor = True
                    progress('已核对抖音账号：' + result['display_name'])
                    return result
            if not allow_wait and self.repository.setting('douyin_session', {}).get('state') == 'WAITING_LOGIN':
                raise ValueError('抖音登录已失效，请点击登录抖音重新扫码')
            self._page.wait_for_timeout(200)
        # Keep observing late QR completion after the waiting worker returns.
        # The UI polls minimal session state; no expired worker callback is kept.
        if allow_wait:self._monitor = True
        raise ValueError('尚未核对到登录账号；可继续在抖音页面完成登录，或再次点击登录检查')

    def _dispose(self):
        context, playwright = self._context, self._playwright
        self._context = self._page = self._playwright = None
        self._candidate = None
        self._monitor = False
        if context is not None:
            try:
                context.close()
            except Exception:
                pass
        if playwright is not None:
            try:
                playwright.stop()
            except Exception:
                pass

    def close(self):
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=10)
