"""Small extension boundaries; concrete implementations live in providers."""
from pathlib import Path
from typing import Protocol, Callable
from threading import Event
from .models import SpeechArtifact

class ContentProvider(Protocol):
    def load(self,path: Path) -> list: ...

class SpeechProvider(Protocol):
    def synthesize(self,request: dict,work: Path,cancel: Event,progress: Callable) -> SpeechArtifact: ...

class Renderer(Protocol):
    def render(self,request: dict,speech: SpeechArtifact,work: Path,cancel: Event,progress: Callable) -> str: ...

class Publisher(Protocol):
    def identity(self,cancel: Event) -> dict: ...
    def upload(self,path: str,account: dict,cancel: Event) -> str: ...
    def submit(self,video_id: str,text: str,account: dict,cancel: Event) -> dict: ...
    def query(self,item_id: str,account: dict,cancel: Event) -> dict: ...
