"""Native page assembly. Production services remain on the window controller."""
from pathlib import Path
from PySide6.QtCore import Qt,QSize
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import (QWidget,QVBoxLayout,QHBoxLayout,QFormLayout,QFrame,QStackedWidget,
    QLineEdit,QComboBox,QPlainTextEdit,QSpinBox,QSlider,QListWidget,QProgressBar,QSplitter,QStyle,QCheckBox)
from PySide6.QtMultimedia import QMediaPlayer,QAudioOutput
from PySide6.QtMultimediaWidgets import QVideoWidget
from .studio_widgets import label,button,page,scroll,divider,STYLE,PortraitPreview
from .release_panels import ReleasePanel


def build_shell(w):
    w.setStyleSheet(STYLE)
    root=QHBoxLayout(w);root.setContentsMargins(0,0,0,0);root.setSpacing(0)
    sidebar=QFrame();sidebar.setObjectName('sidebar');sidebar.setFixedWidth(200)
    side=QVBoxLayout(sidebar);side.setContentsMargins(16,30,16,20);side.setSpacing(10)
    brand=label('映小助','section');side.addWidget(brand)
    side.addWidget(label('让工厂被更多人看到','muted'));side.addSpacing(24)
    w.nav={}
    entries=[('home','工作台',QStyle.SP_DesktopIcon),('materials','素材库',QStyle.SP_DirIcon),('content','文案库',QStyle.SP_FileIcon),('videos','我的视频',QStyle.SP_MediaPlay),('publications','发布记录',QStyle.SP_FileDialogDetailedView)]
    for key,title,icon in entries:
        b=button(title,lambda checked=False,k=key:w.navigate(k),icon=icon);b.setProperty('nav',True);b.setCheckable(True);side.addWidget(b);w.nav[key]=b
    side.addStretch()
    for key,title,icon in [('account','账号与设置',QStyle.SP_ComputerIcon),('help','帮助',QStyle.SP_DialogHelpButton)]:
        b=button(title,lambda checked=False,k=key:w.navigate(k),icon=icon);b.setProperty('nav',True);b.setCheckable(True);side.addWidget(b);w.nav[key]=b
    side.addWidget(label('本地制作 · 首版','muted'));root.addWidget(sidebar)
    column=QVBoxLayout();column.setContentsMargins(0,0,0,0);column.setSpacing(0);root.addLayout(column,1)
    w.pages=QStackedWidget();column.addWidget(w.pages,1)
    w.home_page,home=page('')
    hero=QHBoxLayout();hero.setSpacing(16);copy=QVBoxLayout();copy.setSpacing(16);copy.addStretch()
    title=label('今天，从第一条视频开始。');title.setStyleSheet('font-size:40px;font-weight:700;');copy.addWidget(title)
    copy.addWidget(label('把车间素材和文案准备好，剩下的跟着步骤走。','muted'))
    copy.addSpacing(16)
    w.home_start=button('制作第一条视频',w.begin_creation,True, QStyle.SP_MediaPlay);w.home_start.setMinimumHeight(64);w.home_start.setStyleSheet("font-size:20px;font-weight:600;");w.home_start.setMaximumWidth(400);copy.addWidget(w.home_start)
    learn=button('看看制作流程',lambda:w.navigate('help'));learn.setProperty('link',True);copy.addWidget(learn);copy.addStretch();hero.addLayout(copy,3)
    art=label();pix=QPixmap(str(Path(__file__).parent/'assets/home-hero.png'))
    art.setPixmap(pix.scaled(390,300,Qt.KeepAspectRatio,Qt.SmoothTransformation));art.setAlignment(Qt.AlignCenter);art.setMinimumWidth(260);hero.addWidget(art,2)
    home.addLayout(hero,3);home.addWidget(divider())
    steps=QHBoxLayout();steps.setSpacing(24)
    for n,title,sub in [('1','选择素材与文案','导入本地拍摄的视频和文档'),('2','试听配音并生成','选择系统声音，开始制作'),('3','预览视频，保存到电脑','查看效果，导出本地视频文件')]:
        l=QVBoxLayout();l.addWidget(label(n+'   '+title,'section'));l.addWidget(label(sub,'muted'));steps.addLayout(l,1)
    home.addLayout(steps);home.addWidget(divider());home.addWidget(label('最近的视频','section'))
    w.recent=QListWidget();w.recent.setIconSize(QSize(42,58));w.recent.setMinimumHeight(100);w.recent.setMaximumHeight(200);w.recent.itemClicked.connect(lambda i:w.open_attempt(i.data(Qt.UserRole)));home.addWidget(w.recent,2)
    w.home_empty=label('还没有制作过视频\n\n生成的视频会保存在这里，随时预览与导出。','muted');w.home_empty.setAlignment(Qt.AlignCenter);home.addWidget(w.home_empty,2)
    home.addWidget(label('本地制作无需登录抖音','muted'));w.pages.addWidget(w.home_page)

    w.creation_page,creation=page('制作视频')
    w.step_labels=[];row=QHBoxLayout()
    for i,text in enumerate(['1  选择素材','2  准备文案','3  配音与画面']):
        b=button(text,lambda checked=False,n=i:w.jump_step(n));row.addWidget(b);w.step_labels.append(b)
    creation.addLayout(row)
    w.wizard=QStackedWidget();creation.addWidget(w.wizard,1)
    material,ml=page('选择视频素材','选择存放同一产品或车间视频的文件夹。原文件保持在原位置。')
    w.material=QLineEdit();w.material.hide();w.material_name=label('尚未选择素材文件夹','section')
    w.material.textChanged.connect(lambda value:(w.material_name.setText(Path(value).name if value else '尚未选择素材文件夹'),w.material_name.setToolTip(value)))
    w.material_button=button('选择素材文件夹',w.pick_material,True,QStyle.SP_DirOpenIcon)
    row=QHBoxLayout();row.addWidget(w.material_name,1);row.addWidget(w.material_button);ml.addLayout(row)
    w.material_status=label('支持 MP4、MOV、MKV、AVI。选择后会检查视频并显示缩略图。','muted');ml.addWidget(w.material_status)
    w.material_list=QListWidget();w.material_list.setIconSize(QSize(120,68));w.material_list.setMinimumHeight(150);ml.addWidget(w.material_list,1)
    w.scan_button=button('检查当前素材',w.scan_current_material);ml.addWidget(w.scan_button)
    ml.setContentsMargins(12,12,12,12);ml.setSpacing(12);w.wizard.addWidget(scroll(material))

    content,cl=page('准备标题与口播','标题用于识别这条视频，口播会逐字用于配音。')
    row=QHBoxLayout();w.import_button=button('导入文档',w.import_excel,True,QStyle.SP_FileIcon);row.addWidget(w.import_button)
    w.new_content=button('直接写一条',w.create_content);row.addWidget(w.new_content);row.addStretch();cl.addLayout(row)
    cl.addWidget(label('支持 TXT、DOCX、Excel。可选择一条或勾选多条制作。','muted'))
    row=QHBoxLayout();w.content_list=QListWidget();w.content_list.setMaximumWidth(250);w.content_list.setMinimumHeight(220)
    w.content_list.currentRowChanged.connect(w.select_content_row);w.content_list.itemChanged.connect(w.set_content_enabled);row.addWidget(w.content_list,1)
    fields=QVBoxLayout();w.title_edit=QLineEdit();w.title_edit.setPlaceholderText('填写视频标题');fields.addWidget(label('视频标题'));fields.addWidget(w.title_edit)
    w.voice_edit=QPlainTextEdit();w.voice_edit.setPlaceholderText('在这里填写口播文案，或先导入本地文档。');w.voice_edit.setMinimumHeight(140);fields.addWidget(label('口播文案'));fields.addWidget(w.voice_edit,1)
    w.content_hint=label('尚未导入文案','muted');fields.addWidget(w.content_hint)
    w.edit_button=button('编辑发布正文与话题',w.edit_content);fields.addWidget(w.edit_button);row.addLayout(fields,3);cl.addLayout(row,1)
    w.selector=QComboBox();w.selector.hide();w.selector.currentIndexChanged.connect(w.show_content)
    w.content_view=QPlainTextEdit();w.content_view.hide()
    w.title_edit.textEdited.connect(w.inline_content_changed);w.voice_edit.textChanged.connect(w.inline_content_changed)
    cl.setContentsMargins(12,12,12,12);cl.setSpacing(12);w.wizard.addWidget(scroll(content))

    audio,al=page('配音与画面','先听一听声音。默认制作带字幕的竖屏视频。')
    form=QFormLayout();form.setSpacing(14);form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow);form.setLabelAlignment(Qt.AlignLeft);al.addLayout(form)
    w.voice=QComboBox();form.addRow('系统声音',w.voice)
    w.rate=QComboBox();w.rate.addItems(['0.8','1.0','1.2']);w.rate.setCurrentIndex(1);form.addRow('语速（1.0 为正常）',w.rate)
    row=QHBoxLayout();w.audition_button=button('试听口播前100字',w.audition,icon=QStyle.SP_MediaPlay);row.addWidget(w.audition_button)
    w.stop_audition=button('停止试听',lambda:w.audition_player.stop());row.addWidget(w.stop_audition);al.addLayout(row)
    al.addWidget(label('系统中文音色由电脑提供；字幕按口播长度估算，生成后请预览核对。','muted'))
    w.more_audio=button('调整画面与背景音乐');w.more_audio.setCheckable(True);al.addWidget(w.more_audio)
    advanced=QWidget();af=QFormLayout(advanced);af.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow);af.setLabelAlignment(Qt.AlignLeft)
    w.resolution=QComboBox();w.resolution.addItems(['1080 × 1920','720 × 1280']);af.addRow('竖屏尺寸',w.resolution)
    w.bgm=QLineEdit();w.bgm.setPlaceholderText('不添加背景音乐');w.bgm_button=button('选择音乐',w.pick_bgm)
    row=QHBoxLayout();row.addWidget(w.bgm,1);row.addWidget(w.bgm_button);row.addWidget(button('移除音乐',w.bgm.clear));af.addRow('背景音乐',row)
    w.volume=QSpinBox();w.volume.setRange(0,100);w.volume.setValue(15);af.addRow('音乐音量 %',w.volume)
    advanced.hide();w.more_audio.toggled.connect(advanced.setVisible);al.addWidget(advanced)
    w.generation_summary=label();al.addWidget(w.generation_summary);al.addStretch()
    w.start_button=button('生成这条视频',w.start_generation,True,QStyle.SP_MediaPlay);w.batch_button=button('生成勾选文案',w.start_batch)
    al.setContentsMargins(12,12,12,12);al.setSpacing(12);w.wizard.addWidget(scroll(audio));w.step_error=label('','error');creation.addWidget(w.step_error)
    row=QHBoxLayout();w.previous=button('上一步',w.previous_step);row.addWidget(w.previous);row.addStretch();w.next_step=button('下一步：准备文案',w.advance_step,True);row.addWidget(w.next_step);row.addWidget(w.batch_button);row.addWidget(w.start_button);creation.addLayout(row)
    w.pages.addWidget(w.creation_page)

    w.release_panel=ReleasePanel(w)
    w.videos_page,vl=page('我的视频','选中一条视频，查看制作结果并保存到电脑。')
    splitter=QSplitter();vl.addWidget(splitter,1);left=QWidget();ll=QVBoxLayout(left);ll.setContentsMargins(0,0,12,0)
    w.video_filter=QComboBox();w.video_filter.addItems(['全部视频','已完成','制作中','未完成']);w.video_filter.currentIndexChanged.connect(w.refresh_studio);ll.addWidget(w.video_filter)
    w.video_list=QListWidget();w.video_list.setIconSize(QSize(48,72));w.video_list.currentItemChanged.connect(w.video_selected);ll.addWidget(w.video_list,1)
    w.video_error=label('','error');ll.addWidget(w.video_error)
    ll.addWidget(w.release_panel.retry_button);splitter.addWidget(left)
    right=QWidget();rl=QVBoxLayout(right);rl.setContentsMargins(12,0,0,0)
    w.video_title=label('选择一条视频','section');rl.addWidget(w.video_title)
    w.video_status=label('生成的视频会出现在左侧。','muted');rl.addWidget(w.video_status)
    w.preview_stack=QStackedWidget();w.video_empty=label('还没有可预览的视频\n\n先制作一条，或从左侧选择已完成的视频。','muted');w.video_empty.setAlignment(Qt.AlignCenter);w.preview_stack.addWidget(w.video_empty)
    w.video=QVideoWidget();w.video_page=PortraitPreview(w.video);w.video_page.setMinimumHeight(200);w.preview_stack.addWidget(w.video_page);rl.addWidget(w.preview_stack,1)
    w.player=QMediaPlayer(w);w.audio=QAudioOutput(w);w.player.setAudioOutput(w.audio);w.player.setVideoOutput(w.video);w.video.videoSink().videoFrameChanged.connect(w.capture_preview_frame)
    w.audition_player=QMediaPlayer(w);w.audition_audio=QAudioOutput(w);w.audition_player.setAudioOutput(w.audition_audio)
    w.player.errorOccurred.connect(lambda *_:w.status.setText('预览暂时不可用：'+w.player.errorString()+'；可打开成片目录'))
    w.seek=QSlider(Qt.Horizontal);w.seek.setRange(0,0);rl.addWidget(w.seek)
    w.time_label=label('00:00 / 00:00','muted');rl.addWidget(w.time_label)
    w.player.durationChanged.connect(lambda d:w.seek.setRange(0,d));w.player.positionChanged.connect(w.seek.setValue);w.player.positionChanged.connect(w.update_playback_time);w.seek.sliderMoved.connect(w.player.setPosition)
    row=QHBoxLayout();w.play=button('播放 / 暂停',w.toggle_play,icon=QStyle.SP_MediaPlay);w.export=button('保存到电脑',w.export_result,True);row.addWidget(w.play);row.addWidget(w.export);rl.addLayout(row)
    row=QHBoxLayout();w.folder=button('打开成片目录',w.open_folder);w.to_publish=button('准备发布这条视频',w.open_publish_page);row.addWidget(w.folder);row.addWidget(w.to_publish);rl.addLayout(row)
    w.save_panel=QWidget();save=QVBoxLayout(w.save_panel);save.setContentsMargins(0,0,0,0);save.setSpacing(8)
    save.addWidget(label('保存视频到电脑','section'))
    w.save_name=QLineEdit();w.save_name.setPlaceholderText('视频文件名.mp4');save.addWidget(w.save_name)
    w.save_destination=QComboBox()
    for name,path in [('下载文件夹',Path.home()/'Downloads'),('桌面',Path.home()/'Desktop'),('当前工作区',w.workspace),('自定义位置','')]:w.save_destination.addItem(name,str(path))
    save.addWidget(w.save_destination);w.save_directory=QLineEdit();w.save_directory.setPlaceholderText('填写已有文件夹的完整路径');w.save_directory.hide();save.addWidget(w.save_directory)
    w.save_destination.currentIndexChanged.connect(lambda i:w.save_directory.setVisible(i==3))
    row=QHBoxLayout();w.confirm_save=button('确认保存',w.save_export,True);row.addWidget(w.confirm_save);row.addWidget(button('返回预览',w.hide_save_panel));save.addLayout(row)
    w.save_panel.hide();rl.addWidget(w.save_panel)
    splitter.addWidget(right);splitter.setSizes([350,600]);w.pages.addWidget(w.videos_page)
    w.publication_page,pl=page('发布记录','上传、提交和公开情况分别显示，不自动发布。');pl.addWidget(w.release_panel);w.publication_scroll=scroll(w.publication_page);w.pages.addWidget(w.publication_scroll)
    w.account_scroll=scroll(w.release_panel.account_page);w.pages.addWidget(w.account_scroll)
    w.help_page,hl=page('从第一条视频开始','按照下面三步制作，不需要先登录账号。')
    for t,d in [('1  选择素材与文案','选择对应产品的视频文件夹，再导入本地文档。TXT / DOCX 第一行是标题，其余文字作为口播；Excel 使用 title、voice_text 两列。'),('2  试听并生成','选择系统声音，试听前100字。背景音乐可以留空。默认竖屏1080p，字幕会自动添加。'),('3  预览与保存','检查口播、画面和字幕，点击“保存到电脑”。只有主动准备发布时才需要抖音账号。')]:hl.addWidget(label(t,'section'));hl.addWidget(label(d,'muted'))
    w.demo_button=button('载入合成示例（会替换当前编辑内容）',w.load_demo_confirmed);hl.addWidget(w.demo_button)
    w.log=QPlainTextEdit();w.log.setReadOnly(True);w.log.setMaximumHeight(180);hl.addWidget(label('诊断详情','section'));hl.addWidget(w.log);hl.addStretch();w.help_scroll=scroll(w.help_page);w.pages.addWidget(w.help_scroll)
    w.progress=QProgressBar();w.progress.setTextVisible(False);w.progress.setMaximumHeight(6);w.progress.hide();column.addWidget(w.progress)
    footer=QHBoxLayout();footer.setContentsMargins(24,6,24,8);w.status=label('正在准备本地制作环境…','muted');footer.addWidget(w.status,1)
    w.cancel_button=button('停止当前操作',w.cancel_job);w.cancel_button.hide();footer.addWidget(w.cancel_button);column.addLayout(footer)
    w.inputs=[w.demo_button,w.import_button,w.selector,w.material,w.material_button,w.scan_button,w.new_content,w.content_list,w.title_edit,w.voice_edit,w.bgm,w.bgm_button,w.voice,w.rate,w.resolution,w.volume,w.start_button,w.edit_button,w.batch_button,w.audition_button]
    for control in (w.voice,w.rate,w.resolution):control.currentIndexChanged.connect(w.update_steps)
    w.bgm.textChanged.connect(w.update_steps);w.volume.valueChanged.connect(w.update_steps)
    w.navigate('home')
